[theme]
primaryColor="#ff9f00"
backgroundColor="#0e1117"
secondaryBackgroundColor="#1b1f2a"
textColor="#e6e6e6"
font="sans serif"

[server]
port = 8501
headless = false
address = "localhost"
runOnSave = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false
